/*
  COD_VUELO VARCHAR2(10) PRIMARY KEY,
  HORA_SALIDA VARCHAR2(15),
  DESTINO VARCHAR2(15),
  PROCEDENCIA VARCHAR2(15),
  PLAZAS_FUMADOR NUMBER(3),
  PLAZAS_NO_FUMADOR NUMBER(3),
  PLAZAS_TURISTA NUMBER(3),
  PLAZAS_PRIMERA NUMBER(3)
 */
package tema2.punto5_5;

/**
 *
 * @author ProfVespertino
 */
public class VistaVuelos extends javax.swing.JFrame {

    /**
     * Creates new form VistaPasajeros
     */
    public VistaVuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoVuelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoraSalida = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(8, 2, 10, 10));

        jLabel1.setText("Código Vuelo");
        jPanel1.add(jLabel1);
        jPanel1.add(jTextFieldCodigoVuelo);

        jLabel2.setText("Hora Salida");
        jPanel1.add(jLabel2);
        jPanel1.add(jTextFieldHoraSalida);

        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3);

        jTextField3.setText("jTextField1");
        jPanel1.add(jTextField3);

        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4);

        jTextField4.setText("jTextField1");
        jPanel1.add(jTextField4);

        jLabel5.setText("jLabel1");
        jPanel1.add(jLabel5);

        jTextField5.setText("jTextField1");
        jPanel1.add(jTextField5);

        jLabel6.setText("jLabel1");
        jPanel1.add(jLabel6);

        jTextField6.setText("jTextField1");
        jPanel1.add(jTextField6);

        jLabel7.setText("jLabel1");
        jPanel1.add(jLabel7);
        jPanel1.add(jSpinner2);

        jLabel8.setText("Plazas Disponible 1ª Clase");
        jPanel1.add(jLabel8);
        jPanel1.add(jSpinner1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 6));

        jButton1.setText("Limpiar");
        jPanel2.add(jButton1);

        jButton2.setText("Alta");
        jPanel2.add(jButton2);

        jButton3.setText("Baja");
        jPanel2.add(jButton3);

        jButton4.setText("Modifición");
        jPanel2.add(jButton4);

        jButton5.setText("Consulta");
        jPanel2.add(jButton5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldCodigoVuelo;
    private javax.swing.JTextField jTextFieldHoraSalida;
    // End of variables declaration//GEN-END:variables
}
